import 'dotenv/config';
import express,{NextFunction,Request,Response} from 'express';
import cors from 'cors';
import http from 'http';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import cron from 'node-cron';
import {Server} from 'socket.io';
import {PrismaClient,Role,TaskStatus,Priority,ActivityType,Prisma} from '@prisma/client';
import {z,ZodError} from 'zod';

const prisma=new PrismaClient();
const app=express(); const httpServer=http.createServer(app);
const origin=process.env.CLIENT_ORIGIN||'http://localhost:5173';
const io=new Server(httpServer,{cors:{origin,methods:['GET','POST','PATCH']}});
app.use(cors({origin})); app.use(express.json());

type AuthReq=Request&{user?:{id:string;role:Role;name:string}};
const env=process.env.JWT_SECRET||'dev-only-change-me';
function token(u:{id:string;role:Role;name:string}){return jwt.sign(u,env,{expiresIn:'8h'});}
function auth(req:AuthReq,res:Response,next:NextFunction){try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))throw new Error('Unauthorized');req.user=jwt.verify(h.slice(7),env) as AuthReq['user'];next();}catch{res.status(401).json({error:{code:'UNAUTHORIZED',message:'Authentication required'}})}}
function roles(...allowed:Role[]){return (req:AuthReq,res:Response,next:NextFunction)=>{if(!req.user||!allowed.includes(req.user.role))return res.status(403).json({error:{code:'FORBIDDEN',message:'Insufficient permissions'}});next();}}
function fail(res:Response,code:string,message:string,status=400,details?:unknown){return res.status(status).json({error:{code,message,...(details?{details}:{})}})}
app.get('/health',(_,res)=>res.json({ok:true,service:'velozity-api'}));
const loginSchema=z.object({email:z.string().email(),password:z.string().min(8)});
app.post('/api/auth/login',async(req,res,next)=>{try{const {email,password}=loginSchema.parse(req.body);const u=await prisma.user.findUnique({where:{email}});if(!u||!(await bcrypt.compare(password,u.passwordHash)))return fail(res,'INVALID_CREDENTIALS','Invalid email or password',401);res.json({token:token({id:u.id,role:u.role,name:u.name}),user:{id:u.id,name:u.name,email:u.email,role:u.role}});}catch(e){next(e)}});
app.get('/api/auth/me',auth,async(req:AuthReq,res)=>{const u=await prisma.user.findUnique({where:{id:req.user!.id},select:{id:true,name:true,email:true,role:true}});res.json({user:u});});
const projectSchema=z.object({name:z.string().min(2).max(120),description:z.string().max(1000).default('')});
app.get('/api/projects',auth,async(req:AuthReq,res,next)=>{try{const where=req.user!.role===Role.ADMIN?{}:{ownerId:req.user!.id};const projects=await prisma.project.findMany({where,include:{owner:{select:{id:true,name:true}},_count:{select:{tasks:true}}},orderBy:{createdAt:'desc'}});res.json({projects});}catch(e){next(e)}});
app.post('/api/projects',auth,roles(Role.ADMIN,Role.PM),async(req:AuthReq,res,next)=>{try{const data=projectSchema.parse(req.body);const p=await prisma.project.create({data:{...data,ownerId:req.user!.id}});await prisma.activity.create({data:{type:ActivityType.PROJECT_CREATED,message:`${req.user!.name} created project ${p.name}`,projectId:p.id,userId:req.user!.id}});res.status(201).json({project:p});}catch(e){next(e)}});
async function canViewProject(user:{id:string;role:Role},projectId:string){if(user.role===Role.ADMIN)return true;const p=await prisma.project.findUnique({where:{id:projectId},include:{tasks:{select:{assigneeId:true}}}});if(!p)return false;if(user.role===Role.PM)return p.ownerId===user.id;return p.tasks.some(t=>t.assigneeId===user.id);}
const taskQuery=z.object({status:z.enum(['TODO','IN_PROGRESS','IN_REVIEW','DONE','OVERDUE']).optional(),priority:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).optional(),from:z.string().datetime().optional(),to:z.string().datetime().optional(),projectId:z.string().optional()});
app.get('/api/tasks',auth,async(req:AuthReq,res,next)=>{try{const q=taskQuery.parse(req.query);const base:Prisma.TaskWhereInput={};if(q.status)base.status=q.status as TaskStatus;if(q.priority)base.priority=q.priority as Priority;if(q.projectId)base.projectId=q.projectId;if(q.from||q.to)base.dueDate={...(q.from?{gte:new Date(q.from)}:{}),...(q.to?{lte:new Date(q.to)}:{})};if(req.user!.role===Role.PM)base.project={ownerId:req.user!.id};else if(req.user!.role===Role.DEVELOPER)base.assigneeId=req.user!.id;const tasks=await prisma.task.findMany({where:base,include:{project:{select:{id:true,name:true,ownerId:true}},assignee:{select:{id:true,name:true}},_count:{select:{activities:true}}},orderBy:[{priority:'desc'},{dueDate:'asc'}]});res.json({tasks});}catch(e){next(e)}});
const taskSchema=z.object({title:z.string().min(2).max(160),description:z.string().max(2000).default(''),projectId:z.string().min(1),assigneeId:z.string().nullable().optional(),priority:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).default('MEDIUM'),dueDate:z.string().datetime()});
app.post('/api/tasks',auth,roles(Role.ADMIN,Role.PM),async(req:AuthReq,res,next)=>{try{const d=taskSchema.parse(req.body);if(!(await canViewProject(req.user!,d.projectId)))return fail(res,'FORBIDDEN','You cannot create tasks in this project',403);const t=await prisma.task.create({data:{...d,dueDate:new Date(d.dueDate),priority:d.priority as Priority},include:{project:true,assignee:true}});await prisma.activity.create({data:{type:ActivityType.TASK_CREATED,message:`${req.user!.name} created ${t.title}`,projectId:t.projectId,taskId:t.id,userId:req.user!.id}});if(t.assigneeId){const n=await prisma.notification.create({data:{userId:t.assigneeId,message:`You were assigned task ${t.title}`}});io.to(`user:${t.assigneeId}`).emit('notification:new',n);}res.status(201).json({task:t});}catch(e){next(e)}});
const statusSchema=z.object({status:z.enum(['TODO','IN_PROGRESS','IN_REVIEW','DONE','OVERDUE'])});
app.patch('/api/tasks/:id/status',auth,async(req:AuthReq,res,next)=>{try{const {status}=statusSchema.parse(req.body);const t=await prisma.task.findUnique({where:{id:req.params.id},include:{project:true,assignee:true}});if(!t||!(await canViewProject(req.user!,t.projectId)))return fail(res,'NOT_FOUND','Task not found',404);if(req.user!.role===Role.DEVELOPER&&t.assigneeId!==req.user!.id)return fail(res,'FORBIDDEN','You can only update your assigned tasks',403);const updated=await prisma.task.update({where:{id:t.id},data:{status:status as TaskStatus}});const message=`${req.user!.name} moved ${t.title} from ${t.status.replace('_',' ')} → ${status.replace('_',' ')}`;const a=await prisma.activity.create({data:{type:ActivityType.TASK_STATUS_CHANGED,message,projectId:t.projectId,taskId:t.id,userId:req.user!.id,metadata:{from:t.status,to:status}}});io.to(`project:${t.projectId}`).emit('activity:new',{...a,user:{name:req.user!.name}});if(status==='IN_REVIEW'&&t.project.ownerId!==req.user!.id){const n=await prisma.notification.create({data:{userId:t.project.ownerId,message:`${t.title} moved to In Review`}});io.to(`user:${t.project.ownerId}`).emit('notification:new',n);}res.json({task:updated,activity:a});}catch(e){next(e)}});
app.get('/api/activity',auth,async(req:AuthReq,res,next)=>{try{const limit=z.coerce.number().int().min(1).max(20).default(20).parse(req.query.limit);let where:Prisma.ActivityWhereInput={};if(req.user!.role===Role.PM)where={project:{ownerId:req.user!.id}};if(req.user!.role===Role.DEVELOPER)where={task:{assigneeId:req.user!.id}};const activity=await prisma.activity.findMany({where,take:limit,orderBy:{createdAt:'desc'},include:{user:{select:{name:true,role:true}},task:{select:{title:true}},project:{select:{name:true}}}});res.json({activity});}catch(e){next(e)}});
app.get('/api/notifications',auth,async(req:AuthReq,res,next)=>{try{const ns=await prisma.notification.findMany({where:{userId:req.user!.id},orderBy:{createdAt:'desc'},take:30});const unread=await prisma.notification.count({where:{userId:req.user!.id,readAt:null}});res.json({notifications:ns,unread});}catch(e){next(e)}});
app.patch('/api/notifications/:id/read',auth,async(req:AuthReq,res,next)=>{try{const n=await prisma.notification.updateMany({where:{id:req.params.id,userId:req.user!.id},data:{readAt:new Date()}});if(!n.count)return fail(res,'NOT_FOUND','Notification not found',404);const unread=await prisma.notification.count({where:{userId:req.user!.id,readAt:null}});io.to(`user:${req.user!.id}`).emit('notification:count',unread);res.json({ok:true,unread});}catch(e){next(e)}});
app.post('/api/notifications/read-all',auth,async(req:AuthReq,res,next)=>{try{await prisma.notification.updateMany({where:{userId:req.user!.id,readAt:null},data:{readAt:new Date()}});io.to(`user:${req.user!.id}`).emit('notification:count',0);res.json({ok:true,unread:0});}catch(e){next(e)}});
app.get('/api/dashboard',auth,async(req:AuthReq,res,next)=>{try{if(req.user!.role===Role.ADMIN){const [projects,tasks,overdue]=await Promise.all([prisma.project.count(),prisma.task.groupBy({by:['status'],_count:true}),prisma.task.count({where:{status:TaskStatus.OVERDUE}})]);return res.json({role:'ADMIN',projects,tasksByStatus:tasks,overdue});}if(req.user!.role===Role.PM){const [projects,priority,due]=await Promise.all([prisma.project.count({where:{ownerId:req.user!.id}}),prisma.task.groupBy({by:['priority'],where:{project:{ownerId:req.user!.id}},_count:true}),prisma.task.findMany({where:{project:{ownerId:req.user!.id},dueDate:{gte:new Date(),lte:new Date(Date.now()+7*86400000)}},orderBy:{dueDate:'asc'},take:10,select:{id:true,title:true,dueDate:true,priority:true}})]);return res.json({role:'PM',projects,tasksByPriority:priority,upcoming:due});}const tasks=await prisma.task.findMany({where:{assigneeId:req.user!.id},orderBy:[{priority:'desc'},{dueDate:'asc'}],include:{project:{select:{name:true}}}});res.json({role:'DEVELOPER',tasks});}catch(e){next(e)}});
const online=new Set<string>();
io.use((socket,next)=>{try{const raw=socket.handshake.auth?.token;if(!raw)return next(new Error('Unauthorized'));socket.data.user=jwt.verify(raw,env);next();}catch{next(new Error('Unauthorized'))}});
io.on('connection',socket=>{const u=socket.data.user as {id:string;role:Role};online.add(u.id);io.emit('presence:count',online.size);socket.join(`user:${u.id}`);socket.on('project:join',(projectId:string)=>socket.join(`project:${projectId}`));socket.on('project:leave',(projectId:string)=>socket.leave(`project:${projectId}`));socket.on('disconnect',()=>{online.delete(u.id);io.emit('presence:count',online.size);});});
cron.schedule('0 * * * *',async()=>{const now=new Date();const overdue=await prisma.task.findMany({where:{dueDate:{lt:now},status:{in:[TaskStatus.TODO,TaskStatus.IN_PROGRESS]}},select:{id:true,projectId:true,title:true}});for(const t of overdue){await prisma.task.update({where:{id:t.id},data:{status:TaskStatus.OVERDUE}});const systemUser=await prisma.user.findFirst({where:{role:Role.ADMIN}});if(systemUser)await prisma.activity.create({data:{type:ActivityType.TASK_STATUS_CHANGED,message:`Scheduler flagged ${t.title} as Overdue`,projectId:t.projectId,taskId:t.id,userId:systemUser.id}});io.to(`project:${t.projectId}`).emit('activity:new',{message:`Scheduler flagged ${t.title} as Overdue`});}});
app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>{if(err instanceof ZodError)return fail(res,'VALIDATION_ERROR','Invalid request data',400,err.issues);console.error(err);return fail(res,'INTERNAL_ERROR','An unexpected error occurred',500);});
const port=Number(process.env.PORT||4000);httpServer.listen(port,()=>console.log(`API listening on ${port}`));
